### ISSUE TITLE
No description

### ISSUE THREAD

**Issue by adam-palazzo** [RichardLitt/extract-id3-tags-from-mp3s#12]
There doesn't seem to be a description for our repo. I recommend using the description in the README, as it's concise and accurate. This also promotes consistency throughout our documentation!

**Comment by RichardLitt** [comment]
There is no description in the README at the moment. What description do you suggest?

**Comment by adam-palazzo** [comment]
The description I added to the README in my pull request is succinct enough; "Extracts id3 tags from an mp3 file"

**Comment by RichardLitt** [comment]
Added. Thanks.
